# Generated by Django 6.1 on 2026-08-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('localidad', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('salud', 'Salud'), ('policiales', 'Policiales'), ('turismo', 'Turismo'), ('festividades', 'Festividades')], max_length=50)),
                ('insight_clave', models.TextField(blank=True, null=True)),
                ('sentimiento', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
