# Generated by Django 5.2.17 on 2026-09-02 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_publicacion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='RegistroDatos',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fuentes_api', models.CharField(max_length=100)),
                ('fecha_ejecucion', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('lenguaje', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Registro_Datos',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id_trends', models.AutoField(primary_key=True, serialize=False)),
                ('relevancia', models.CharField(max_length=50)),
                ('intervalos_periodo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Trends',
            },
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='fuente',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='insight_clave',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='sentimiento',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='id_publicacion_api',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='publicacion',
            table='Publicacion',
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_revision', models.DateTimeField()),
                ('estado_aprobacion', models.CharField(max_length=2)),
                ('id_publicacion_api', models.ForeignKey(db_column='id_publicacion_api', on_delete=django.db.models.deletion.CASCADE, to='core.publicacion')),
            ],
            options={
                'db_table': 'Auditoria',
            },
        ),
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id_locacion', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=18)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('id_publicacion_api', models.ForeignKey(db_column='id_publicacion_api', on_delete=django.db.models.deletion.CASCADE, to='core.publicacion')),
            ],
            options={
                'db_table': 'Locacion',
            },
        ),
        migrations.CreateModel(
            name='PublicacionTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publicacion_api', models.ForeignKey(db_column='id_publicacion_api', on_delete=django.db.models.deletion.CASCADE, to='core.publicacion')),
            ],
            options={
                'db_table': 'Publicacion_Temas',
            },
        ),
        migrations.AddField(
            model_name='publicacion',
            name='id_registro',
            field=models.ForeignKey(blank=True, db_column='id_registro', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.registrodatos'),
        ),
        migrations.CreateModel(
            name='Sentimiento',
            fields=[
                ('id_sentimiento', models.AutoField(primary_key=True, serialize=False)),
                ('polaridad', models.FloatField()),
                ('confianza', models.FloatField()),
                ('id_publicacion_api', models.ForeignKey(db_column='id_publicacion_api', on_delete=django.db.models.deletion.CASCADE, to='core.publicacion')),
            ],
            options={
                'db_table': 'Sentimiento',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_temas', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('publicaciones', models.ManyToManyField(related_name='temas', through='core.PublicacionTema', to='core.publicacion')),
            ],
            options={
                'db_table': 'Temas',
            },
        ),
        migrations.AddField(
            model_name='publicaciontema',
            name='id_temas',
            field=models.ForeignKey(db_column='id_temas', on_delete=django.db.models.deletion.CASCADE, to='core.tema'),
        ),
        migrations.CreateModel(
            name='TemaTrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_temas', models.ForeignKey(db_column='id_temas', on_delete=django.db.models.deletion.CASCADE, to='core.tema')),
                ('id_trends', models.ForeignKey(db_column='id_trends', on_delete=django.db.models.deletion.CASCADE, to='core.trend')),
            ],
            options={
                'db_table': 'Temas_Trends',
                'unique_together': {('id_temas', 'id_trends')},
            },
        ),
        migrations.AddField(
            model_name='tema',
            name='trends',
            field=models.ManyToManyField(related_name='temas', through='core.TemaTrend', to='core.trend'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserAuditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_auditoria', models.ForeignKey(db_column='id_auditoria', on_delete=django.db.models.deletion.CASCADE, to='core.auditoria')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'User_Auditoria',
                'unique_together': {('id_user', 'id_auditoria')},
            },
        ),
        migrations.AddField(
            model_name='auditoria',
            name='usuarios',
            field=models.ManyToManyField(related_name='auditorias', through='core.UserAuditoria', to='core.user'),
        ),
        migrations.AlterUniqueTogether(
            name='publicaciontema',
            unique_together={('id_publicacion_api', 'id_temas')},
        ),
        migrations.CreateModel(
            name='VotoPublicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_voto', models.CharField(max_length=50)),
                ('fecha_voto', models.DateTimeField()),
                ('id_publicacion_api', models.ForeignKey(db_column='id_publicacion_api', on_delete=django.db.models.deletion.CASCADE, to='core.publicacion')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'Votos_Publicacion',
                'unique_together': {('id_user', 'id_publicacion_api')},
            },
        ),
    ]
