# Generated by Django 5.2.17 on 2026-10-03 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_registrodatos_role_trend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha_captura',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fuente',
            field=models.CharField(default='El Territorio', max_length=100),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='hash_origen',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='procesado_ia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='id_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.registrodatos'),
        ),
    ]
